backend:
  name: git-gateway
  branch: master
local_backend: true
media_folder: data/media
public_folder: media

collections:
  - name: "pages"
    label: "Pages"
    description: "You can edit the pages of your website here"
    files: 
      - label: 'Image Example'
        name: 'image-example'
        file: data/pages/image-example.json
        delete: false
        fields:
          - { label: 'Content', name: 'content', widget: 'markdown' }
          - { label: "Image", name: "thumbnail", widget: "image" }
              
  - name: "settings"
    label: "Settings"
    delete: false
    description: "Manage settings including your sites title, description and keywords."
    summary: "Metadata"
    files:
      - label: 'Metadata'
        name: 'metadata'
        file: data/settings.json
        delete: false
        fields:
          - { label: "Site title", name: "site_title", widget: "string" }
          - { label: "Site description", name: "site_description", widget: "string" }
          - { label: "URL", name: "base_url", widget: "string", hint: "Do not enter the trailing slash of the URL" }
          - { label: "Preview thumbnail", name: "thumbnail", widget: "image" }
          - { label: "Site keywords", name: "site_keywords", widget: "string", hint: 'Use a comma to separate keywords. E.g Photography, Portfolio, Prints'}
          - { label: "Instagram account", name: "instagram_account", widget: "string" }