backend:
  name: git-gateway
  branch: main

# This line should *not* be indented
media_folder: "public/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads"



collections:
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "content/pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{path}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Path", name: "path", widget: "string", required: false}
      - {label: "Title", name: "title", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "sitePart" # Used in routes, e.g., /admin/collections/blog
    label: "Site Part" # Used in the UI
    folder: "content/siteParts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{name}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
  
  - name: "testimonial" # Used in routes, e.g., /admin/collections/blog
    label: "Testimonial" # Used in the UI
    folder: "content/testimonials" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Wedding Date", name: "weddingDate", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "whyFact" # Used in routes, e.g., /admin/collections/blog
    label: "Why Fact" # Used in the UI
    folder: "content/whyFacts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "howItWorksSlide"
    label: "How It Works Slide"
    folder: "content/howItWorksSlide" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{order}}-{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string", required: false}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Type", name: "type", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}



