backend:
  name: git-gateway
  branch: main

# This line should *not* be indented
media_folder: "public/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads"



collections:
  - name: "sitePart" # Used in routes, e.g., /admin/collections/blog
    label: "SiteParts" # Used in the UI
    folder: "content/siteParts" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Content", name: "content", widget: "markdown"}
  
  - name: "testimonial" # Used in routes, e.g., /admin/collections/blog
    label: "Testimonials" # Used in the UI
    folder: "content/testimonials" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Wedding Date", name: "weddingDate", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "whyFact" # Used in routes, e.g., /admin/collections/blog
    label: "Why Facts" # Used in the UI
    folder: "content/whyFacts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}



